config/routes.rb
Rails.application.routes.draw do
	
  get 'errors/not_found'

  get 'errors/internal_server_error'

  resources :listings do 
    member do
      post :add_to_cart
      delete :remove_from_cart
    end
  end

resources :listings, :path => "/collections/all"

resources :charges 
resources :checkout
resources :shipping
resources :orders
resource :cart
resources :admins
resources :pictures
resources :users
resources :collections
resources :coupons

match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all
get "/listings-new" => "listings#new"
get "/listings-tops" => "listings#tops"
get "/listings-tees" => "listings#tees"
get "/listings-long_sleeves" => "listings#long_sleeves"
get "/listings-short_sleeves" => "listings#short_sleeves"
get "/listings-jackets" => "listings#jackets"
get "/listings-hoodies" => "listings#hoodies"
get "/listings-bottoms" => "listings#bottoms"
get "/listings-denim" => "listings#denim"
get "/listings-trousers" => "listings#trousers"
get "/listings-shorts" => "listings#shorts"
get "/listings-head" => "listings#head"
get "/listings-accessories" => "listings#accessories"
get "/listings-sale" => "listings#sale"
get "/listings-hidden" => "listings#hidden"
get "/pre_spring_2017" => "listings#pre_spring_2017"
get "/fall_winter_2016" => "listings#fall_winter_2016"
get "/spring_summer_2016" => "listings#spring_summer_2016"
get "/fall_winter_2015" => "listings#fall_winter_2015"
get "/judgement_day_capsule" => "listings#judgement_day_capsule"

get  "/admin"  => "session#new"
post "/session"      => "session#create"
get  "/logout"       => "session#destroy"

root "welcome#index"

get "/index" => "welcome#index"
get "/springsummersixteen" => "welcome#springsummersixteen"
get "/media" => "welcome#media"
get "/brand" => "welcome#brand"
get "/press" => "welcome#press"

post "make_default" => "pictures#make_default"
get "/complete" => "welcome#complete"
get "/customercare" => "customers#index"

end

app/models/listing.rb
class Listing < ApplicationRecord
	# has_attached_file :pictures, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	# validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	has_many :pictures
	has_one :default_picture, ->{ reorder(default: :desc) }, class_name: "Picture"
	
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
		skip_before_filter  :verify_authenticity_token

		def under_construction
		end
		

	def index
		

		if params[:remove]
			Listing.delete(params[:remove])
		end
		
		@listings = Listing.all.order(price: :desc)

		@listings_new = Listing.where(:section => "New").order(id: :desc)
		@listings_hoodies= Listing.where(:section => "Hoodies").order(id: :desc)
		@listings_long_sleeves= Listing.where(:section => "Long Sleeves").order(id: :desc)
		@listings_short_sleeves= Listing.where(:section => "Short Sleeves").order(id: :desc)
		@listings_tees= Listing.where(:section => "Tees").order(id: :desc)
		@listings_tanks= Listing.where(:section => "Tanks").order(id: :desc)
		@listings_jackets = Listing.where(:section => "Jackets").order(id: :desc)
		@listings_bottoms = Listing.where(:section => "Bottoms").order(id: :desc)
		@listings_denim = Listing.where(:section => "Denim").order(id: :desc)
		@listings_trousers = Listing.where(:section => "Trousers").order(id: :desc)
		@listings_shorts = Listing.where(:section => "Shorts").order(id: :desc)
		@listings_head = Listing.where(:section => "Head").order(id: :desc)
		@listings_wristwear = Listing.where(:section => "Wristwear").order(id: :desc)
		@listings_accessories = Listing.where(:section => "Accessories").order(id: :desc)
		
		@listings_press = Listing.where(:section => "Press")
		@listings_collection = Listing.where(:section => "Collection").order(:fabric)



		
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @listings }
    end

	end


	def new
		@listing = Listing.new
	 	render :layout => false 

	end



	def create
		@listing = Listing.new(listing_params)

		respond_to do |format|
			if @listing.save
				if params[:images]
					params[:images].each {|image|
						@listing.pictures.create(image: image)
					}

				end

		format.html { redirect_to @listing, notice: 'listing was successfully created.' }
      format.json { render json: @listing, status: :created, location: @listing }
    else
      format.html { render action: "new" }
      format.json { render json: @listing.errors, status: :unprocessable_entity }
    end
  end
end

	

	def show
		if params[:id]
			session[:cart] ||= {}
		@listing = Listing.find(params[:id])
		@count_cart = session[:cart].count + 2
		end	


	  # Amount in cents
	  	
	  	@amount = @listing.price
	  	@listings = Listing.all

	  	@listing  = Listing.find(params[:id])
    	@pictures = @listing.pictures.order(:description)



    # LISTING UPDATE
    
	end

	def edit 
		@listing = Listing.find(params[:id])
	end


	
	 def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(listing_params)
        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @listing.pictures.create(image: image)
          }
        end
        format.html { redirect_to @listing, notice: 'listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  	end


	def destroy
		@listing = Listing.find(params[:id])
		@listing.destroy
			if @listing.destroy
				redirect_to "/listings"
			end

	end

	def add_to_cart
		session[:cart] ||= {} # Creating an empty hash
		key = [params[:id], params[:size]].join('-') # creating a key = to the listing, size joined with a "-"
		session[:cart][key] = (session[:cart][key] || 0) + 1 #setting the key inside of the session hash to the listing object or 0, every time a key is set, it increments by 1
		redirect_to :cart 
	end

	def remove_from_cart
		session[:cart].delete(params[:id])
		redirect_to :cart
	end

	def tops
		@listings_hoodies= Listing.where(:section => "Hoodies").order(id: :desc)
		@listings_long_sleeves= Listing.where(:section => "Long Sleeves").order(id: :desc)
		@listings_short_sleeves= Listing.where(:section => "Short Sleeves").order(id: :desc)
		@listings_tanks= Listing.where(:section => "Tanks").order(id: :desc)
		@listings_tees= Listing.where(:section => "Tees").order(id: :desc)

	end	

	def tees
		@listings_tees= Listing.where(:section => "Tees").order(id: :desc)

	end


	def jackets
		@listings_jackets = Listing.where(:section => "Jackets").order(id: :desc)
	end

	def hoodies
		@listings_hoodies= Listing.where(:section => "Hoodies").order(id: :desc)
	end

	def bottoms
		@listings_denim = Listing.where(:section => "Denim").order(id: :desc)
		@listings_trousers = Listing.where(:section => "Trousers").order(id: :desc)
		@listings_shorts = Listing.where(:section => "Shorts").order(id: :desc)
		
	end

	def denim
		@listings_denim = Listing.where(:section => "Denim").order(id: :desc)
	end	

	def trousers
		@listings_trousers = Listing.where(:section => "Trousers").order(id: :desc)
	end

	def shorts
		@listings_shorts = Listing.where(:section => "Shorts").order(id: :desc)
	end



	def long_sleeves
		@listings_long_sleeves = Listing.where(:section => "Long Sleeves").order(id: :desc)
	end	

	def short_sleeves
		@listings_short_sleeves = Listing.where(:section => "Short Sleeves").order(id: :desc)
		@listings_tees= Listing.where(:section => "Tees").order(id: :desc)

	end


	def accessories
		@listings_accessories = Listing.where(:section => "Accessories").order(id: :desc)		
	end

	def head
		@listings_head = Listing.where(:section => "Head").order(id: :desc)	
	end

	def sale
		@listings_sale = Listing.where(:on_sale => "true").order(id: :desc)	
	end

	def hidden
		@listings_hidden = Listing.where(:is_hidden => "true")

	end


	def fall_winter_2016
		@listings_fall_winter_2016 = Listing.where(:collection => "FALL/WINTER2016").order(id: :desc)	
	end	

	def pre_spring_2017
		@listings_pre_spring_2017 = Listing.where(:collection => "PRE-SPRING 17").order(id: :desc)	
	end	

	def spring_summer_2016
		@listings_spring_summer_2016 = Listing.where(:collection => "SPRING/SUMMER2016").order(id: :desc)	
	end	

	def fall_winter_2015
		@listings_fall_winter_2015 = Listing.where(:collection => "FALL/WINTER2015").order(id: :desc)	
	end

	def judgement_day_capsule
		@listings_judgement_day_capsule = Listing.where(:collection => "JUDGEMENTDAYCAPSULE").order(id: :desc)	
	end








	private

	def listing_params
		params.require(:listing).permit(:name, :price, :original_price, :images, :size, :pictures, :description, :section, :collection, :fabric, :fit, :care, :position, :on_sale, :is_new, :is_hidden, :size_guide)

	end
	


end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/bottoms.html.erb
	<%= javascript_include_tag "application.js" %>

<title>Bottoms</title>

<hr style="width:100%;" class="mobile-hr-hidden">
<!-- <div id="listings-sidebar">
	<ul id="listings-sidebar-list">
		<li><a href="/listings">ALL</a></li>
<li><a href="/listings-jackets">JACKETS</a></li>
		<li><a href="/listings-tops">TOPS</a></li>
		<li><a href="/listings-hoodies">HOODIES</a></li>
		<li><a href="/listings-long_sleeves">LONG SLEEVES</a></li>
		<li><a href="/listings-short_sleeves">SHORT SLEEVES</a></li>
		<li><a href="/listings-tees">T-SHIRTS</a></li>
		<li><a href="/listings-bottoms">BOTTOMS</a></li>
		<li><a href="/listings-denim">DENIM</a></li>
		<li><a href="/listings-trousers">TROUSERS</a></li>
		<li><a href="/listings-shorts">SHORTS</a></li>
		<li><a href="/listings-head">HEADWEAR</a></li>
		<li><a href="/listings-accessories">BAGS</a></li>
	</ul>

</div>
 -->




<table class="products" id="denim">
	<tr>
		<td class="col">
			<ul>

			<h1 class="product-heading-h1">DENIM</h1>

			<% @listings_denim.each do |listing| %>

				<% if listing.is_hidden %> 
				<li style="display:none;"></li>

			<%else%>

				<% if listing.default_picture %>
            	<li>
            	<!-- listing image pictures -->
		           <figure class="listings-figure"> 	
		            	<%= link_to image_tag(listing.default_picture.image.url), listing_path(listing) %>
		           <a href="<%=listing_path(listing)%>">
		            	<figcaption class="listings-figcaption"> 

		            		<p> 
		            			<%= listing.name.upcase %><br><br><br> 
		            			<%=	listing.description.upcase.html_safe%> <br><br>
		            			<% if listing.on_sale == false %> <!-- IF LISTING IS NOT ON SALE -->
			            			<span style="padding:0px;color:black;">

			            				$<%= listing.price %>.00

			            			</span>
			            		<% else %>
									<span style="padding:0px;color:red;">

			            				$<%= listing.price %>.00

			            			</span>
									<span style="padding: 0px;text-decoration: line-through;">

										$<%= listing.original_price %>.00

									</span>
								<% end %>
		            		</p> 

		            	</figcaption>
		           </a>

		           <p class="mobile-figure-p"><%= listing.name.upcase %></p>
				<p class="mobile-figure-p"><%= listing.price %> USD</p>
		            	<% else %>
		              		N/A
		            	<% end %>
		           </figure>
						
						<!-- Name, price and buttons -->
				<form id="index-form" method="get">
				<input type="hidden" name="id" value="<%=listing.id%>">
				<!-- <a href="<%=listing_path(listing)%>"><%=listing.name %></a><br>  -->
				<!-- <p>$<%=listing.price %>.00</p><br> -->
				<!-- <div class="line-separator"></div> -->
				
				 <!-- <br/> -->
							 <% if logged_in? %>
							<p><%=link_to 'Edit', edit_listing_path(listing) %></p>
							<p><a href="?remove=<%=listing.id%>">Delete</a></p><br>
							<% end %>
							<!-- <br> -->
							<!-- <br> -->
				</form>	

				</li>
			<% end %>
				<% end %>
			</ul>
		</td>
	</tr>
</table>


<hr>



<table class="products" id="trousers">
	<tr>
		<td class="col">
			<ul>

			<h1 class="product-heading-h1">TROUSERS</h1>

			<% @listings_trousers.each do |listing| %>

				<% if listing.is_hidden %> 
				<li style="display:none;"></li>

			<%else%>

				<% if listing.default_picture %>
            	<li>
            	<!-- listing image pictures -->
		           <figure class="listings-figure"> 	
		            	<%= link_to image_tag(listing.default_picture.image.url), listing_path(listing) %>
		           <a href="<%=listing_path(listing)%>">
		            	<figcaption class="listings-figcaption"> 

		            		<p> 
		            			<%= listing.name.upcase %><br><br><br> 
		            			<%=	listing.description.upcase.html_safe%> <br><br>
		            			<% if listing.on_sale == false %> <!-- IF LISTING IS NOT ON SALE -->
			            			<span style="padding:0px;color:black;">

			            				$<%= listing.price %>.00

			            			</span>
			            		<% else %>
									<span style="padding:0px;color:red;">

			            				$<%= listing.price %>.00

			            			</span>
									<span style="padding: 0px;text-decoration: line-through;">

										$<%= listing.original_price %>.00

									</span>
								<% end %>
		            		</p> 

		            	</figcaption>
		           </a>

		           <p class="mobile-figure-p"><%= listing.name.upcase %></p>
				<p class="mobile-figure-p"><%= listing.price %> USD</p>
		            	<% else %>
		              		N/A
		            	<% end %>
		           </figure>
						
						<!-- Name, price and buttons -->
				<form id="index-form" method="get">
				<input type="hidden" name="id" value="<%=listing.id%>">
				<!-- <a href="<%=listing_path(listing)%>"><%=listing.name %></a><br>  -->
				<!-- <p>$<%=listing.price %>.00</p><br> -->
				<!-- <div class="line-separator"></div> -->
				
				 <!-- <br/> -->
							 <% if logged_in? %>
							<p><%=link_to 'Edit', edit_listing_path(listing) %></p>
							<p><a href="?remove=<%=listing.id%>">Delete</a></p><br>
							<% end %>
							<!-- <br> -->
							<!-- <br> -->
				</form>	

				</li>
			<% end %>
				<% end %>
			</ul>
		</td>
	</tr>
</table>



<table class="products" id="shorts">
	<tr>
		<td class="col">
			<ul>

			<h1 class="product-heading-h1">SHORTS</h1>

			<% @listings_shorts.each do |listing| %>

				<% if listing.is_hidden %> 
				<li style="display:none;"></li>

			<%else%>

				<% if listing.default_picture %>
            	<li>
            	<!-- listing image pictures -->
		           <figure class="listings-figure"> 	
		            	<%= link_to image_tag(listing.default_picture.image.url), listing_path(listing) %>
		           <a href="<%=listing_path(listing)%>">
		            	<figcaption class="listings-figcaption"> 

		            		<p> 
		            			<%= listing.name.upcase %><br><br><br> 
		            			<%=	listing.description.upcase.html_safe%> <br><br>
		            			<% if listing.on_sale == false %> <!-- IF LISTING IS NOT ON SALE -->
			            			<span style="padding:0px;color:black;">

			            				$<%= listing.price %>.00

			            			</span>
			            		<% else %>
									<span style="padding:0px;color:red;">

			            				$<%= listing.price %>.00

			            			</span>
									<span style="padding: 0px;text-decoration: line-through;">

										$<%= listing.original_price %>.00

									</span>
								<% end %>
		            		</p> 

		            	</figcaption>
		           </a>

		           <p class="mobile-figure-p"><%= listing.name.upcase %></p>
				<p class="mobile-figure-p"><%= listing.price %> USD</p>
		            	<% else %>
		              		N/A
		            	<% end %>
		           </figure>
						
						<!-- Name, price and buttons -->
				<form id="index-form" method="get">
				<input type="hidden" name="id" value="<%=listing.id%>">
				<!-- <a href="<%=listing_path(listing)%>"><%=listing.name %></a><br>  -->
				<!-- <p>$<%=listing.price %>.00</p><br> -->
				<!-- <div class="line-separator"></div> -->
				
				 <!-- <br/> -->
							 <% if logged_in? %>
							<p><%=link_to 'Edit', edit_listing_path(listing) %></p>
							<p><a href="?remove=<%=listing.id%>">Delete</a></p><br>
							<% end %>
							<!-- <br> -->
							<!-- <br> -->
				</form>	

				</li>
			<% end %>
				<% end %>
			</ul>
		</td>
	</tr>
</table>

app/views/listings/fall_winter_2015.html.erb
<%= javascript_include_tag "application.js" %>

<title>FALL \ WINTER 2015</title>
	<h1 class="logo-text-h1">MERCY X MANKIND</h1>
	<h3 class="logo-text-h3">NEW YORK</h3>
	<hr>

	<div id="listings-index-div">
		<ul id="listings-index-nav">
			<li><a href="/listings">ALL</a></li>
			<li>OUTERWEAR</li>
				<ul class="hidden-nav" id="listings-outerwear-nav-hidden">
					<li><a href="/listings-jackets">JACKETS</a></li>
				</ul>
			<li>APPAREL</li>
				<ul class="hidden-nav" id="listings-apparel-nav-hidden">
					<li><a href="/listings-tops">TOPS</a></li>
					<li><a href="/listings-bottoms">BOTTOMS</a></li>
				</ul>
			<li><a href="listings-head">HEADWEAR</a></li>
			<li><a href="listings-accessories">BAGS</a></li>
			<li><a href="/collections">LOOKBOOKS</a></li>
			<li><a style="color: red;" href="/listings-sale">SALE</a></li>
			
			<br>

		</ul>

	</div>




<table class="products" id="fall_winter_2015">
	<tr>
		<td class="col">
			<ul>
			<h1 class="product-heading-h1">FALL \ WINTER 2015</h1>


			<% @listings_fall_winter_2015.each do |listing| %>

				<% if listing.default_picture %>
            	<li>
            	<!-- listing image pictures -->
		           <figure class="listings-figure"> 	
		            	<%= link_to image_tag(listing.default_picture.image.url), listing_path(listing) %>
		           <a href="<%=listing_path(listing)%>">
		            	<figcaption class="listings-figcaption"> 

		            		<p> 
		            			<%= listing.name.upcase %><br><br><br> 
		            			<%=	listing.description.upcase.html_safe%> <br><br>
		            			<% if listing.on_sale == false %> <!-- IF LISTING IS NOT ON SALE -->
			            			<span style="padding:0px;color:black;">

			            				$<%= listing.price %>.00

			            			</span>
			            		<% else %>
									<span style="padding:0px;color:red;">

			            				$<%= listing.price %>.00

			            			</span>
									<span style="padding: 0px;text-decoration: line-through;">

										$<%= listing.original_price %>.00

									</span>
								<% end %>
		            		</p> 

		            	</figcaption>
		           </a>
		            	<% else %>
		              		N/A
		            	<% end %>
		           </figure>
						
						<!-- Name, price and buttons -->
				<form id="index-form" method="get">
				<input type="hidden" name="id" value="<%=listing.id%>">
				<!-- <a href="<%=listing_path(listing)%>"><%=listing.name %></a><br>  -->
				<!-- <p>$<%=listing.price %>.00</p><br> -->
				<!-- <div class="line-separator"></div> -->
				
				 <!-- <br/> -->
							 <% if logged_in? %>
							<p><%=link_to 'Edit', edit_listing_path(listing) %></p>
							<p><a href="?remove=<%=listing.id%>">Delete</a></p><br>
							<% end %>
							<!-- <br> -->
							<!-- <br> -->
				</form>	

				</li>
				<% end %>
			</ul>
		</td>
	</tr>
</table>

app/views/listings/fall_winter_2016.html.erb
<%= javascript_include_tag "application.js" %>

<title>FALL \ WINTER 2016</title>
	<h1 class="logo-text-h1">MERCY X MANKIND</h1>
	<h3 class="logo-text-h3">NEW YORK</h3>
	<hr>

	<div id="listings-index-div">
		<ul id="listings-index-nav">
			<li><a href="/listings">ALL</a></li>
			<li>OUTERWEAR</li>
				<ul class="hidden-nav" id="listings-outerwear-nav-hidden">
					<li><a href="/listings-jackets">JACKETS</a></li>
				</ul>
			<li>APPAREL</li>
				<ul class="hidden-nav" id="listings-apparel-nav-hidden">
					<li><a href="/listings-tops">TOPS</a></li>
					<li><a href="/listings-bottoms">BOTTOMS</a></li>
				</ul>
			<li><a href="listings-head">HEADWEAR</a></li>
			<li><a href="listings-accessories">BAGS</a></li>
			<li><a href="/collections">LOOKBOOKS</a></li>
			<li><a style="color: red;" href="/listings-sale">SALE</a></li>
			
			<br>

		</ul>

	</div>




<table class="products" id="fall_winter_2016">
	<tr>
		<td class="col">
			<ul>
			<h1 class="product-heading-h1">FALL \ WINTER 2016</h1>


			<% @listings_fall_winter_2016.each do |listing| %>

				<% if listing.default_picture %>
            	<li>
            	<!-- listing image pictures -->
		           <figure class="listings-figure"> 	
		            	<%= link_to image_tag(listing.default_picture.image.url), listing_path(listing) %>
		           <a href="<%=listing_path(listing)%>">
		            	<figcaption class="listings-figcaption"> 

		            		<p> 
		            			<%= listing.name.upcase %><br><br><br> 
		            			<%=	listing.description.upcase.html_safe%> <br><br>
		            			<% if listing.on_sale == false %> <!-- IF LISTING IS NOT ON SALE -->
			            			<span style="padding:0px;color:black;">

			            				$<%= listing.price %>.00

			            			</span>
			            		<% else %>
									<span style="padding:0px;color:red;">

			            				$<%= listing.price %>.00

			            			</span>
									<span style="padding: 0px;text-decoration: line-through;">

										$<%= listing.original_price %>.00

									</span>
								<% end %>
		            		</p> 

		            	</figcaption>
		           </a>
		            	<% else %>
		              		N/A
		            	<% end %>
		           </figure>
						
						<!-- Name, price and buttons -->
				<form id="index-form" method="get">
				<input type="hidden" name="id" value="<%=listing.id%>">
				<!-- <a href="<%=listing_path(listing)%>"><%=listing.name %></a><br>  -->
				<!-- <p>$<%=listing.price %>.00</p><br> -->
				<!-- <div class="line-separator"></div> -->
				
				 <!-- <br/> -->
							 <% if logged_in? %>
							<p><%=link_to 'Edit', edit_listing_path(listing) %></p>
							<p><a href="?remove=<%=listing.id%>">Delete</a></p><br>
							<% end %>
							<!-- <br> -->
							<!-- <br> -->
				</form>	

				</li>
				<% end %>
			</ul>
		</td>
	</tr>
</table>

app/views/listings/head.html.erb
<%= javascript_include_tag "application.js" %>

<title>Headwear</title>

<hr style="width:100%;" class="mobile-hr-hidden">
<!-- <div id="listings-sidebar">
	<ul id="listings-sidebar-list">
		<li><a href="/listings">ALL</a></li>
<li><a href="/listings-jackets">JACKETS</a></li>
		<li><a href="/listings-tops">TOPS</a></li>
		<li><a href="/listings-hoodies">HOODIES</a></li>
		<li><a href="/listings-long_sleeves">LONG SLEEVES</a></li>
		<li><a href="/listings-short_sleeves">SHORT SLEEVES</a></li>
		<li><a href="/listings-tees">T-SHIRTS</a></li>
		<li><a href="/listings-bottoms">BOTTOMS</a></li>
		<li><a href="/listings-denim">DENIM</a></li>
		<li><a href="/listings-trousers">TROUSERS</a></li>
		<li><a href="/listings-shorts">SHORTS</a></li>
		<li><a href="/listings-head">HEADWEAR</a></li>
		<li><a href="/listings-accessories">BAGS</a></li>
	</ul>

</div>
 -->


<table class="products" id="head">
	<tr>
		<td class="col">
			<ul>
			<h1 class="product-heading-h1">HEADWEAR</h1>

			<% @listings_head.each do |listing| %>

				<% if listing.is_hidden %> 
				<li style="display:none;"></li>

			<%else%>

				<% if listing.default_picture %>
            	<li>
            	<!-- listing image pictures -->
		           <figure class="listings-figure"> 	
		            	<%= link_to image_tag(listing.default_picture.image.url), listing_path(listing) %>
		           <a href="<%=listing_path(listing)%>">
		            	<figcaption class="listings-figcaption"> 

		            		<p> 
		            			<%= listing.name.upcase %><br><br><br> 
		            			<%=	listing.description.upcase.html_safe%> <br><br>
		            			<% if listing.on_sale == false %> <!-- IF LISTING IS NOT ON SALE -->
			            			<span style="padding:0px;color:black;">

			            				$<%= listing.price %>.00

			            			</span>
			            		<% else %>
									<span style="padding:0px;color:red;">

			            				$<%= listing.price %>.00

			            			</span>
									<span style="padding: 0px;text-decoration: line-through;">

										$<%= listing.original_price %>.00

									</span>
								<% end %>
		            		</p> 

		            	</figcaption>
		           </a>

		           <p class="mobile-figure-p"><%= listing.name.upcase %></p>
				<p class="mobile-figure-p"><%= listing.price %> USD</p>
		            	<% else %>
		              		N/A
		            	<% end %>
		           </figure>
						
						<!-- Name, price and buttons -->
				<form id="index-form" method="get">
				<input type="hidden" name="id" value="<%=listing.id%>">
				<!-- <a href="<%=listing_path(listing)%>"><%=listing.name %></a><br>  -->
				<!-- <p>$<%=listing.price %>.00</p><br> -->
				<!-- <div class="line-separator"></div> -->
				
				 <!-- <br/> -->
							 <% if logged_in? %>
							<p><%=link_to 'Edit', edit_listing_path(listing) %></p>
							<p><a href="?remove=<%=listing.id%>">Delete</a></p><br>
							<% end %>
							<!-- <br> -->
							<!-- <br> -->
				</form>	

				</li>
			<% end %>
				<% end %>
			</ul>
		</td>
	</tr>
</table>