config/routes.rb
Rails.application.routes.draw do
	
  get 'errors/not_found'

  get 'errors/internal_server_error'

  resources :listings do 
    member do
      post :add_to_cart
      delete :remove_from_cart
    end
  end

resources :listings, :path => "/collections/all"

resources :charges 
resources :checkout
resources :shipping
resources :orders
resource :cart
resources :admins
resources :pictures
resources :users
resources :collections
resources :coupons

match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all
get "/listings-new" => "listings#new"
get "/listings-tops" => "listings#tops"
get "/listings-tees" => "listings#tees"
get "/listings-long_sleeves" => "listings#long_sleeves"
get "/listings-short_sleeves" => "listings#short_sleeves"
get "/listings-jackets" => "listings#jackets"
get "/listings-hoodies" => "listings#hoodies"
get "/listings-bottoms" => "listings#bottoms"
get "/listings-denim" => "listings#denim"
get "/listings-trousers" => "listings#trousers"
get "/listings-shorts" => "listings#shorts"
get "/listings-head" => "listings#head"
get "/listings-accessories" => "listings#accessories"
get "/listings-sale" => "listings#sale"
get "/listings-hidden" => "listings#hidden"
get "/pre_spring_2017" => "listings#pre_spring_2017"
get "/fall_winter_2016" => "listings#fall_winter_2016"
get "/spring_summer_2016" => "listings#spring_summer_2016"
get "/fall_winter_2015" => "listings#fall_winter_2015"
get "/judgement_day_capsule" => "listings#judgement_day_capsule"

get  "/admin"  => "session#new"
post "/session"      => "session#create"
get  "/logout"       => "session#destroy"

root "welcome#index"

get "/index" => "welcome#index"
get "/springsummersixteen" => "welcome#springsummersixteen"
get "/media" => "welcome#media"
get "/brand" => "welcome#brand"
get "/press" => "welcome#press"

post "make_default" => "pictures#make_default"
get "/complete" => "welcome#complete"
get "/customercare" => "customers#index"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
  def index
  	session[:cart] ||= {}
	session[:cart][params[:id]] = [params[:id], params[:name], params[:desc],params[:price]]
			
      @listings_head = Listing.where(:section => "Head")

      @listings_slideshow = Listing.where(:section => "Slideshow")
      @listing = @listings_slideshow[2]
      @pictures = @listings_slideshow[2].pictures.order(description: :asc) 

      @listings = Listing.all.order(price: :desc)
      
 



    @listings_new = Listing.where(:section => "New")
    @listings_hoodies= Listing.where(:section => "Hoodies")
    @listings_long_sleeves= Listing.where(:section => "Long Sleeves")
    @listings_short_sleeves= Listing.where(:section => "Short Sleeves")
    @listings_tees= Listing.where(:section => "Tees")
    @listings_tanks= Listing.where(:section => "Tanks")
    @listings_jackets = Listing.where(:section => "Jackets")
    @listings_bottoms = Listing.where(:section => "Bottoms")
    @listings_denim = Listing.where(:section => "Denim")
    @listings_head = Listing.where(:section => "Head")
    @listings_wristwear = Listing.where(:section => "Wristwear")
    @listings_accessories = Listing.where(:section => "Accessories")


  end

  def media
  end

  def springsummersixteen
  end

  def complete
  end
  
  def brand
  end
    

  def press
    @listings_press = Listing.where(:section => "Press").order(description: :desc) 
  end
  
  
  

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/brand.html.erb
	<%= javascript_include_tag "application.js" %>
<title>Brand | MXMNY</title>


	<div id="brand-div">
		<h3>Obsession.</h3>
		<p>Mercy X Mankind is the ultimate rendition of designer Isaac Saqib. <br>It is the culmination of an inspired mind filled with chaos expressed as textiles and designs. <br>Through exploration of self and life in the depths of the concrete haven that is New York City, Saqib exhibits his supreme expression as a way to connect with other human minds. </p>
		<p>Textiles are sourced internationally, garments are manufactured in New York. </p> 
	</div>

app/views/welcome/complete.html.erb
<%= javascript_include_tag "application.js" %>






<div style="text-align: center;">

<p class="order-complete-text">Thank you for your order! You should be receieving an email shortly. If you have any questions please email us at: </p>


<a href="mailto:info@mercyxmankind.com" class="order-complete-text">info@mercyxmankind.com</a>

<br>

<h3>Follow us!</h3>

<a href="http://www.facebook.com/mercytomankindclothing"><%= image_tag "/assets/fb-58ff3d888e5c394dfdd6d78aa5b52c7e1c94d670bd56748a3fbeccbaaccb217b.png" , :class => 'icons-complete' %></a>

<a href="http://www.instagram.com/mercytomankind.ny"><%=image_tag '/assets/ig-037022b92da8534b4952f8b40e0171749e0334ac41d2cfdfd774a0ef52443819.png', :class => 'icons-complete' %></a>

</div>

app/views/welcome/home.html.erb
<%= javascript_include_tag "application.js" %>

	<h1 style=" padding-top: 40px;font-family: 'Raleway';letter-spacing: 7px;">MERCY X MANKIND</h1>
	<h3 style="    font-family: 'Raleway';margin-bottom: 50px;padding-right: 25px;">NEW YORK</h3>
<object controls="0" style="width:820px; height: 461.25px;" data="http://www.youtube.com/embed/lx0l3Dg8sp8?modestbranding=1;autohide=1&amp;showinfo=0&amp;controls=0">
</object>

app/views/welcome/index.html.erb
<html>
	<head>
		<title> MERCY X MANKIND NEW YORK </title>
		<%= javascript_include_tag "application.js" %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<!-- BEGIN PRIVY WIDGET CODE -->
		<script type='text/javascript'> var _d_site = _d_site || '39F45F7BD0352326343B684B'; </script>
		<script src='//widget.privy.com/assets/widget.js'></script>
		<!-- END PRIVY WIDGET CODE -->
		<meta name="description" content="MERCY X MANKIND NEW YORK | Contemporary Urbanwear For The Modern Being | SPRING/SUMMER 2016 Available Now."/>
	</head>


<div class="wrapper">

<body>

<!-- DESKTOP SWIPER  -->
  <div class="swiper-container1">
    <div style="height:650px;margin-bottom: 15px;" id="#index-swiper-wrapper" class="swiper-wrapper">
		    <% @listing_desktop_index_slide = Listing.find_by_id(266) %>
			<% @pictures = @listing_desktop_index_slide.pictures.order(description: :asc)  %>
			<% @pictures.each do |pic| %>
			<% if logged_in? %>

			      <div class="swiper-slide">
			      	<a href="/listings/<%=@listing_desktop_index_slide.id%>">
						<img style="width: 98%" class="list-pic-index" src="<%=pic.image.url%>">
					</a>
			      </div>

			    <% else %>

			      <div class="swiper-slide">
		   		 	<a href="/<%=pic.link%>">
						<img class="list-pic-index" src='<%= pic.image.url %>'>
			      	</a> 
			      </div>
				<% end %>
      		<% end %>


    </div>

    <div style="left:35px;" class="swiper-button-prev swiper-button-white"></div>
    <div style="right:35px;" class="swiper-button-next swiper-button-white"></div>
    
    <!-- Add Pagination -->
    <div id="swiper1-pag" class="swiper-pagination"></div>

  </div> 

<!-- END DESKTOP SWIPER-->



 <!-- MOBILE SWIPER -->
  <div class="swiper-container2">
    <div style="height:1300px; margin-bottom: 15px;" id="#index-swiper-wrapper" class="swiper-wrapper">
		    <% @listings_mobile_index_slide = Listing.find_by_id(267) %>
			<% @pictures = @listings_mobile_index_slide.pictures.order(description: :asc)  %>
			<% @pictures.each do |pic| %>
			<% if logged_in? %>
		      
		      <div class="swiper-slide">
		      	<a href="/listings/<%=@listings_mobile_index_slide.id%>">
					<img class="list-pic" src="<%=pic.image.url%>">
				</a>
		      </div>
		    <%else%>

		      <div class="swiper-slide">
	   		 	<a href="/<%=pic.link%>">
					<img class="list-pic" src="<%=pic.image.url%>" %>
		      	</a>
		      </div>
		      <% end %>

      	<% end %>
    </div>

    <!-- Add Pagination -->
        <div style="left:35px;" class="swiper-button-prev swiper-button-white"></div>
    <div style="right:35px;" class="swiper-button-next swiper-button-white"></div>
    
    <div style="height:70px;z-index: 100;" class="swiper-pagination"></div>

  </div> 
  <!-- END MOBILE SWIPER  -->


<!--
<div id="shipping-box">
	<p>FREE SHIPPING + FREE RETURNS ( USA ONLY ) </p>
</div>  
-->

<hr>

		
   <h3 class="index-section-titles">MEDIA</h3>

  	<ul id="media-list"> 
   		<li>
		  	<a href="/collections/269"><img src="/assets/media-list-1-chris.jpg"></a>  	
  		</li>   		   		

  		<li>
		  	<a href="/brand"><img src="/assets/media-list-2 2.jpg"></a>  	
  		</li>   		

  		<li>
		  	<a href="http://www.instagram.com/mercytomankind.ny"><img src="assets/media-list-3 3.jpg"></a>  	
  		</li>
  	</ul>

<hr>

	<h3 id="film-heading" class="index-section-titles">EXPLORE</h3>
	<!-- MOBILE INDEX VIEO - HIDDEN ON DESKTOP-->
	 <iframe id="index-film" src="https://player.vimeo.com/video/259062808" width="920" height="680" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
	<!-- END MOBILE INDEX VIDEO  -->

	<!-- DESKTOP FILM LSIT -->
  	<ul id="film-list">

   		<li>
		  	<a href="/media"><img class="film-list-img" src="assets/film-list-3-76cfb08207bf9c840bd9806627bce52585e4293860006db55659d3d2b7590a45.jpg"></a><br>
		  	<p style="font-size: 10px;margin:10px 0px;font-family: 'Helvetica';font-weight: bold;">
		  		"THE DEPTHS"
		  	</p>
  		</li>   		

  		<li>
		  	<a href="/collections/269"><img class="film-list-img" src="assets/film-list-text.jpg"></a><br>
		  	<!-- <p style="font-size: 10px;margin: 10px 0px;font-family: 'Helvetica';font-weight: bold;"></p>	 -->
  		</li>   		

  	</ul>

<hr>	

	<%
	@listings = Listing.all.order(price: :desc)
	  @limited_shuffle_mobile = @listings.first(25).shuffle
      @limited_final_mobile = @limited_shuffle_mobile.first(6)
      %>
			<% @listings_press = Listing.where(:section => "Press") %>
			<% @listings_press.each do |listing| %>
				<% if @limited_final_mobile.include? listing %>
					<% @limited_final_mobile.delete(listing) %>
				<% end %>
			<% end %>

		<% @listings_slideshow = Listing.where(:section => "Slideshow") %>
			<% @listings_slideshow.each do |listing| %>
				<% if @limited_final_mobile.include? listing %>
					<% @limited_final_mobile.delete(listing) %>
				<% end %>
			<% end %>	
		<% @listings_collection = Listing.where(:section => "Collection") %>
			<% @listings_collection.each do |listing| %>
				<% if @limited_final_mobile.include? listing %>
					<% @limited_final_mobile.delete(listing) %>
				<% end %>
			<% end %>	


	<h3 style="margin-bottom: 20px;" class="index-section-titles">POPULAR</h3>
	<!-- MOBILE PRODUCT TABLE - HIDDEN ON DESKTOP -->
	<table class="products" id="mobile-product-table">
	<tr>
 		<td class="col">
			<ul id="listings_on_welcome_index">

			<div class="mobile-line-separator"></div>
			<% @limited_final_mobile.each do |listing| %>
            	<li>
	            	<figure class="listings-figure"> 	
			            	
			        <%= link_to image_tag(listing.default_picture.image.url), listing_path(listing) %>
			            	
	            	<a href="<%=listing_path(listing)%>">
			            	<figcaption class="listings-figcaption"> 

			            		<p> 
									<%= listing.name.upcase %><br><br><br> 
			            			<%=	listing.description.upcase.html_safe%> <br><br>
			            			
			            			<% if listing.on_sale == false %> <!-- IF LISTING IS NOT ON SALE -->
				            			<span style="padding:0px;color:black;">

				            				$<%= listing.price %>.00

				            			</span>
				            		<% else %>
										<span style="padding:0px;color:red;">

				            				$<%= listing.price %>.00

				            			</span>
										<span style="padding: 0px;text-decoration: line-through;">

											$<%= listing.original_price %>.00

										</span>
									<% end %>

			            		</p> 

			            	</figcaption>
					</a>
					<p class="mobile-figure-p"><%= listing.name.upcase %></p>
					<p class="mobile-figure-p"><%= listing.price %> USD</p> 

		           </figure>

			

				</li>
				<% end %>
				</ul>
			</td>
		</tr>
	</table>
<!-- END MOBILE PRODUCT TABLE  -->


		 <% @upsell_listings_arr = @listings.sample(2) %> 

	<%
	@listings = Listing.all.order(price: :desc)
	  @limited_shuffle = @listings.first(25).shuffle
      @limited_final_desktop = @limited_shuffle.first(4)
    %>
		<!-- Randomly selecting two listings and creating a new array containing them-->
			
		<!-- REMOVING ANY LISTINGS FROM SECTIONS PRESS, SLIDESHOW AND COLLECTION  -->

		<% @listings_press = Listing.where(:section => "Press") %>
			<% @listings_press.each do |listing| %>
				<% if @limited_final_desktop.include? listing %>
					<% @limited_final_desktop.delete(listing) %>
				<% end %>
			<% end %>

		<% @listings_slideshow = Listing.where(:section => "Slideshow") %>
			<% @listings_slideshow.each do |listing| %>
				<% if @limited_final_desktop.include? listing %>
					<% @limited_final_desktop.delete(listing) %>
				<% end %>
			<% end %>	
		<% @listings_collection = Listing.where(:section => "Collection") %>
			<% @listings_collection.each do |listing| %>
				<% if @limited_final_desktop.include? listing %>
					<% @limited_final_desktop.delete(listing) %>
				<% end %>
			<% end %>	

<!-- DESKTOP PRODUCT LIST -->
	<ul id="desktop-products-list">
		<% @limited_final_desktop.each do |listing| %>
	    	
	    	<li>    	
		        <%= link_to image_tag(listing.default_picture.image.url), listing_path(listing) %>
 				<p class="desktop-products-list-text"><%= listing.name.upcase %></p>
				<p class="desktop-products-list-text"><%= listing.price %> USD</p>  
			</li>
		<% end %>
	</ul>
<!-- END DESKTOP PRODUCT LIST -->


<!-- End Wrapper -->
</div>

</body>

</html>

app/views/welcome/media.html.erb
<%= javascript_include_tag "application.js" %>
			<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>

<title>Media | MXMNY</title>




<iframe class="media-iframe" src="https://player.vimeo.com/video/259062808" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<h5 style="font-family: 'Helvetica';letter-spacing: 3px;">"THE DEPTHS"</h5>

<iframe class="media-iframe" src="https://player.vimeo.com/video/255202089" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<h5 style="font-family: 'Helvetica';letter-spacing: 3px;">MERCY X MANKIND NEW YORK: "NOTHING COMES EASY"</h5>

<br>

<iframe class="media-iframe" src="https://player.vimeo.com/video/216327730" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<h5 style="font-family: 'Helvetica';letter-spacing: 3px;">PRE-SPRING 17': "GODSEND"</h5>


<br>

<iframe class="media-iframe" src="https://player.vimeo.com/video/192698295" width="740" height="460" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<h5 style="font-family: 'Helvetica';letter-spacing: 3px;">FALL/WINTER 2016 CAMPAIGN FILM.DELIVERY ONE.</h5>

<br>
<!-- <p> Music: SAVAGE - P.Soul</p> -->

<iframe class="media-iframe" src="https://player.vimeo.com/video/192707456" width="740" height="460" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<h5 style="font-family: 'Helvetica';letter-spacing: 3px;">SPRING/SUMMER 2016 CAMPAIGN FILM</h5>


<!-- <p> Music: Ghost (Prod. Trooh Hippi) </p> -->
<br>

<iframe class="media-iframe" src="https://player.vimeo.com/video/192706677" width="740" height="460" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<h5 style="font-family:'Helvetica';letter-spacing: 3px;">MERCY X MANKIND NEW YORK: "WHERE DOES YOUR CONFIDENCE COME FROM?"</h5>	

app/views/welcome/press.html.erb
<%= javascript_include_tag "application.js" %>


<title>Press</title>



				<hr class="mobile-hr-hidden">

<!--   <ul class="press-list">
	<% @listings_press.each do |listing| %>
		<li>
			<h1 style="text-decoration: underline;"><%=listing.name%></h1>
			<p><%=listing.description.html_safe%></p>

			<% @pictures = listing.pictures.order(description: :asc) %>

			<% @pictures.each do |pic| %>
				<% if logged_in? %>
					<a href="/listings/<%=listing.id%>"><img src="<%=pic.image.url%>"></a>
				<%else%>
					<img src="<%=pic.image.url%>">
				<% end %>
			<% end %>
			
		</li>
	<% end %>
  </ul>
 -->


	


  <ul class="press-index-list">
		<% @listings_press.each do |listing| %>
					<% if listing.default_picture %>

			<li>
	            	<%= link_to image_tag(listing.default_picture.image.url), collection_path(listing) %>
	            			<p><%= listing.name %></p>
	            	<% else %>
	              		N/A
	            	<% end %>
			</li>
			
		<% end %>

  </ul>

app/views/welcome/springsummersixteen.html.erb
<div class="wrapper">

<h1>MERCY X MANKIND</h1>
<h3>NEW YORK</h3>

<img style="width:820px;height:480px;"src="assets/ss16-c5e545c669dbab2d2d4e8e8376f5fb92545c9317d3f841727064207b63ae2d02.JPG">


</div>