config/routes.rb
Rails.application.routes.draw do
	
  get 'errors/not_found'

  get 'errors/internal_server_error'

  resources :listings do 
    member do
      post :add_to_cart
      delete :remove_from_cart
    end
  end

resources :listings, :path => "/collections/all"

resources :charges 
resources :checkout
resources :shipping
resources :orders
resource :cart
resources :admins
resources :pictures
resources :users
resources :collections
resources :coupons

match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all
get "/listings-new" => "listings#new"
get "/listings-tops" => "listings#tops"
get "/listings-tees" => "listings#tees"
get "/listings-long_sleeves" => "listings#long_sleeves"
get "/listings-short_sleeves" => "listings#short_sleeves"
get "/listings-jackets" => "listings#jackets"
get "/listings-hoodies" => "listings#hoodies"
get "/listings-bottoms" => "listings#bottoms"
get "/listings-denim" => "listings#denim"
get "/listings-trousers" => "listings#trousers"
get "/listings-shorts" => "listings#shorts"
get "/listings-head" => "listings#head"
get "/listings-accessories" => "listings#accessories"
get "/listings-sale" => "listings#sale"
get "/listings-hidden" => "listings#hidden"
get "/pre_spring_2017" => "listings#pre_spring_2017"
get "/fall_winter_2016" => "listings#fall_winter_2016"
get "/spring_summer_2016" => "listings#spring_summer_2016"
get "/fall_winter_2015" => "listings#fall_winter_2015"
get "/judgement_day_capsule" => "listings#judgement_day_capsule"

get  "/admin"  => "session#new"
post "/session"      => "session#create"
get  "/logout"       => "session#destroy"

root "welcome#index"

get "/index" => "welcome#index"
get "/springsummersixteen" => "welcome#springsummersixteen"
get "/media" => "welcome#media"
get "/brand" => "welcome#brand"
get "/press" => "welcome#press"

post "make_default" => "pictures#make_default"
get "/complete" => "welcome#complete"
get "/customercare" => "customers#index"

end

app/models/picture.rb
class Picture < ApplicationRecord
 has_attached_file :image

  belongs_to :listing

  do_not_validate_attachment_file_type :image




end

app/controllers/pictures_controller.rb
  class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
    skip_before_filter  :verify_authenticity_token

  def index

    @listing = Listing.find(params[:id])

    @pictures = @listing.pictures.order(description: :desc) 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @listing = Listing.find(params[:listing_id])
    @picture = @listing.pictures.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    #@gallery = Gallery.find(params[:gallery_id])

    @picture = Picture.find(params[:id])
      if @picture.save 
        redirect_to "/listings"
      else
        render :edit
      end

    # @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    if @picture.save
      respond_to do |format|
        format.html {
          render :json => [@picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@picture.to_jq_upload].to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update

    # @listing = Listing.find(params[:listing_id])

    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to "/listings"
    else
      render :edit
    end
    
     
  end
  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    #@gallery = Gallery.find(params[:gallery_id])
    #@picture = @gallery.pictures.find(params[:id])
    @picture = Picture.find(params[:id])
    @picture.destroy
      if @picture.destroy
        redirect_to @picture.listing
      end
      
  end

  def make_default
    @picture = Picture.find(params[:id])
    @listing = Listing.find(params[:listing_id])

    @listing.cover = @picture.id
    @listing.save

    respond_to do |format|
      format.js
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:default, :description, :listing_id, :image, :link)
  end
end

app/views/pictures/_form.html.erb
<%= form_for [@listing, @picture], :html => { :class => 'form-horizontal' } do |f| %>

    <%= f.label :description, :class => 'control-label' %>

      <%= f.text_field :description, :class => 'text_field' %>


  
    <%= image_tag @picture.image.large.url, :id => 'cropbox' %>
  
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>


    <%= f.submit nil, :class => 'btn btn-primary  btn-mini' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                listing_path(@listing), :class => 'btn btn-mini' %>
    <%= link_to 'Default', '', :class => 'btn btn-mini btn-success' , :id => 'make_default'%>


<% end %>

<script type="text/javascript" charset="utf-8">
    $(function () {
      $('#make_default').click(function(event) {
        event.preventDefault();
        $.ajax({
          url: '<%= make_default_listing_pictures_path %>',
          type: 'POST',
          data: {id : <%= @picture.id %>, listing_id : <%= @listing.id %>}
        });
      });
    });
</script>

app/views/pictures/destroy.js.erb
$('#picture_<%= @picture.id %>').fadeOut();

app/views/pictures/edit.html.erb
  <h1 class="h1-headers">Edit Picture</h1>


<%= form_for @picture do |f| %>

    <%= image_tag @picture.image.url %><br>
    <%= f.label :description %>

    <%= f.text_field :description%><br>

    <%= f.label :default %>
    <%= f.check_box :default %>

   
  	<%= link_to "Delete picture", @picture, :method => :delete,
                                      data: { confirm: "You sure?" } %>

 
    <%= f.submit  %>
    <% end %>

app/views/pictures/index.html.erb
<%- model_class = Picture.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:listing_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to picture.id, picture_path(picture) %></td>
        <td><%= picture.description %></td>
        <td><%= picture.image %></td>
        <td><%= picture.listing_id %></td>
        <td><%=l picture.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_picture_path(picture), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      picture_path(picture),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_picture_path,
            :class => 'btn btn-primary' %>

app/views/pictures/new.html.erb
<%= form_for [@listing, @picture], :html => { :class => 'form-horizontal' } do |f| %>

    <%= f.label :description, :class => 'control-label' %>

      <%= f.text_field :description, :class => 'text_field' %>


  
    <%= image_tag @picture.image.large.url, :id => 'cropbox' %>
  
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>


    <%= f.submit nil, :class => 'btn btn-primary  btn-mini' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                listing_path(@listing), :class => 'btn btn-mini' %>
    <%= link_to 'Default', '', :class => 'btn btn-mini btn-success' , :id => 'make_default'%>


<% end %>

<script type="text/javascript" charset="utf-8">
    $(function () {
      $('#make_default').click(function(event) {
        event.preventDefault();
        $.ajax({
          url: "/make_default_listing_pictures_path",
          type: 'POST',
          data: {id : <%= @picture.id %>, listing_id : <%= @listing.id %>}
        });
      });
    });
</script>

app/views/pictures/show.html.erb
<title>MERCY X MANKIND NY</title>

<%= form_for @picture do |f| %>

    <%= image_tag @picture.image.url, :class => "picture-edit", :id => "draggable"  %><br>
    
    <% if logged_in? %>
    <%= f.label :description %>
    <%= f.text_field :description%><br>
    <%= f.label :default %>
    <%= f.check_box :default %>


  	<%= link_to "Delete picture", @picture, :method => :delete,
                                      data: { confirm: "You sure?" } %>

  
 
    <%= f.submit  %>
    <% end %>

<% end %>